### ISSUE TITLE
[Feat/EPIC-260-PP] Responsive Pages

### ISSUE THREAD

**Issue by minsu26** [STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION#148]
## 🌊 **Epic Description**
PP main, about, artwork, contact, faq, news, recruit 등의 페이지들 반응형 페이지로 수정

## 🏄🏻‍♂️ **Scrum Description**

- 261: About Page

- [x] PP-About Page의 tablet 기준 반응형 페이지 완성하기
- [x] PP-About Page의 mobile 기준 반응형 페이지 완성하기
 
 
- 263: Contact Page

- [ ] PP-Contact Page의 tablet 기준 반응형 페이지 완성하기
- [x] PP-Contact Page의 mobile 기준 반응형 페이지 완성하기

- 264: FAQ Page

- [ ] PP-FAQ Page의 tablet 기준 반응형 페이지 완성하기
- [x] PP-FAQ Page의 mobile 기준 반응형 페이지 완성하기

- 267: Recruitment Page

- [x] PP-Recruitment Page의 tablet 기준 반응형 페이지 완성하기
- [x] PP-Recruitment Page의 mobile 기준 반응형 페이지 완성하기

## 💬 **Comment**
> 기타로 공유할 사항들을 작성해주세요
