### ISSUE TITLE
[Feat/EPIC-245-PP] Recruitment Page

### ISSUE THREAD

**Issue by minsu26** [STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION#149]
## 🌊 **Epic Description**
PP Recruitment 페이지 생성

## 🏄🏻‍♂️ **Scrum Description**
- 249: Recruitment Page
- [ ] 기업 정보를 확인할 수 있는 링크로 이동 가능
- [ ] 현재 등록된 채용공고 확인 및 해당 공고를 상세히 볼 수 있는 링크로 이동 가능
- [ ] 기업의 사내 복지 확인 가능

## 💬 **Comment**
> 추후 반응형 페이지로 수정 예정

**Comment by minsu26** [comment]
Responsive page까지 완료
