### ISSUE TITLE
feat/EPIC-175-pp

### ISSUE THREAD

**Issue by kimgoat** [STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION#39]
## 🌊 **Epic Description**
일반 사용자는 새로 디자인한 PP 페이지를 조회할 수 있다.

## 🏄🏻‍♂️ **Scrum Description**
- scrum 176 (민수)
- [x] 일반 사용자는 새로 디자인한 PP-Contact 페이지를 조회할 수 있다.

- scrum 177 (영서)
- [x] 일반 사용자는 새로 디자인한 PP-Artwork 페이지를 조회할 수 있다.

- scrum 178 (보현)
- [x] 일반 사용자는 새로 디자인한 PP-Main 페이지 (+ Header, Footer)를 조회할 수 있다.
