### ISSUE TITLE
feat/EPIC-212-edit

### ISSUE THREAD

**Issue by kimgoat** [STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION#44]
## 🌊 **Epic Description**

홍보 관리자는 정보 관리 Page에 접속하여 PP 페이지 내용을 조회하고 수정할 수 있다. 

## 🏄🏻‍♂️ **Scrum Description**
- scrum 205
- [x] 홍보관리자는 회사 소개 정보를 조회 및 수정할 수 있다.

- scrum 206
- [x] 홍보관리자는 협력사 정보를 조회 및 수정할 수 있다.

- scrum 207
- [x] 홍보관리자는 CEO 정보를 조회 및 수정할 수 있다.

- scrum 208
- [x] 홍보관리자는 회사 기본 정보를 조회 및 수정할 수 있다.

- scrum 209
- [x] 홍보관리자는 클라이언트 정보를 조회 및 수정할 수 있다.

- scrum 210
- [x] 홍보관리자는 5가지 회사 상세 정보를 조회 및 수정할 수 있다.

- scrum 233
- [x] 직원은 프로모션 관리자 페이지에서 새롭게 디자인된 Data Edit 탭의 Company 수정/등록/조회 페이지를 확인할 수 있다.

## 💬 **Comment**

~~기타로 공유할 사항들을 작성해주세요.~~
