### ISSUE TITLE
feat/EPIC-122-faq

### ISSUE THREAD

**Issue by kimgoat** [STUDIO-EYE/STUDIO-EYE-WEB-PROMOTION#9]
## 🌊 **Epic Description**
홍보 관리자는 프로모션 관리자 페이지에서 faq를 등록, 수정, 삭제할 수 있다.

## 🏄🏻‍♂️ **Scrum Description**
- scrum 121
- [x] 일반 사용자는 프로모션 페이지에서 faq를 조회할 수 있다.

- scrum 123
- [x] 홍보 관리자는 프로모션 관리자 faq페이지에서 faq를 삭제할 수 있다.

- scrum 124
- [x] 홍보 관리자는 프로모션 관리자 faq페이지에서 faq를 등록할 수 있다.

- scrum 125
- [x] 홍보 관리자는 프로모션 관리자 faq페이지에서 faq를 수정할 수 있다.

## 💬 **Comment**
scrum 121을 민수님이 맡아주시면 됩니다!!
